[project]
name = "bs4demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "whitebig17-sys", email = "whitebig17@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
bs4demo = "bs4demo:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
